name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
          
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npx start-server-and-test start http://localhost:4100 cypress
          spec: cypress/e2e/home.cy.ts
          wait-on: 'http://localhost:4100'
