
name: Cypress Tests

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Start server
        run: npm start
      - name: Wait for server
        run: |
          npm install wait-on -g
          wait-on http://localhost:4100 --timeout 30000
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          start: |
            npm run cypress:run
          wait-on: 'http://localhost:4100'
