name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start server
        run: |
            npm install -g serve
            npm serve -s build

      - name: Wait for server
        run: |
          npm install wait-on
          wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          start: |
            npm run cypress:run
          wait-on: 'http://localhost:3000'
